### ISSUE TITLE
Chaining in banners is counterproductive

### ISSUE THREAD

**Issue by thefowles1** [LaughingQuoll/Unify#14]
Chaining is a great feature to this tweak, but I believe it shouldn't apply to notifications in every iteration, especially banners. Considering the small display area for notification text in a banner, this causes some severe issues with long or multiple text messages. With chaining enabled and the phone unlocked, receiving a long text message defeats the purpose of chaining; if the message length reaches the end of the banner and is truncated, any subsequent incoming messages will not be visible in the banners, as the tweak is chaining these subsequent messages _after_ the initial long text message, and instead the banners will continue to show the first received text message repeatedly.

I believe users should have the option to select where chaining applies -- LS, NC, and banners -- individually.

**Comment by LaughingQuoll** [comment]
This is not an issue, but a feature request. Request noted.

**Comment by thefowles1** [comment]
Oops. Thanks.
