### ISSUE TITLE
can't swipe right on notifications with today view hidden.

### ISSUE THREAD

**Issue by imperialnymph** [LaughingQuoll/Unify#18]
swiping right to open a notification will fail when having tweaks that hide lock screen's today view (_nottoday10, notodayview_) enabled.

issue does not exist when unify is disabled, or today view is not hidden.

tested on 5s, 10.2.
not sure if this issue persists on 3D touch devices.

**Comment by LaughingQuoll** [comment]
Cannot replicate. Tested on 5s, SE and 6s.

**Comment by LaughingQuoll** [comment]
Actually...

I can replicate on ealier builds. I've fixed this without realising.
